### ISSUE TITLE
"Start Tracing" Not Found

### ISSUE THREAD

**Issue by Arunraj89** [codedx/codepulse#16]
I have installed Code pulse latest build 1.1.4(Win X64) on Win 10 64bit machine. I have used Sample OWASP Shepherd application. I have configured the agent with Tomcat and started the application and application is running good. But i could not locate the "START TRACE" button as it mentioned in user guide.  because of which when i trace the shepherd app, its not getting traced in the code pulse. Please help me to solve this issue.

**Comment by baffles** [comment]
Sorry to hear you're having trouble getting tracing going. Do you have Code Pulse up and running before you start Tomcat? If so, do you see a pop up similar to the one below?

![Tracing popup](https://github.com/secdec/codepulse/wiki/resources/trace-connected-status.png)

There are more details [here](https://github.com/secdec/codepulse/wiki/Tracing-Projects#initializing-a-trace) on starting a trace if you are seeing this popup.

**Comment by Arunraj89** [comment]
Yes I have started Code Pulse before starting Tomcat,but I don't get any notification/pop-up like what you show above.

**Comment by baffles** [comment]
How did you configure the agent with Tomcat? You'll want to make sure it's added to `CATALINA_OPTS` in `setenv.bat`. It may help to make sure that the path to the agent jar file does not contain spaces as well.

**Comment by dylemma** [comment]
Nine months with no response; I'm going to assume he figured it out.
