### ISSUE TITLE
Option to automatically start tracing

### ISSUE THREAD

**Issue by skirge** [codedx/codepulse#20]
Please add an option to automatically start tracing (without confirmation in GUI), preferably with possibility of setting session name from tracer command line argument. 
I hava an application with a lot of short tests (setup app in Docker and stopping it after the test) which end before I can confirm.

**Comment by stevesalas** [comment]
[Code Pulse v2.6.2](https://github.com/codedx/codepulse/releases/tag/v2.6.2) includes a feature to skip trace acknowledgment for [Java](https://github.com/codedx/codepulse/wiki/user-guide#skip-java-trace-user-acknowledgment) and [.NET](https://github.com/codedx/codepulse/wiki/user-guide#skip-net-trace-user-acknowledgment).
