### ISSUE TITLE
Upload jar file failed, just showed: Error: <html><head><title>Error</title></head><body> <h2>ERROR: </h2> <br> </body></html>

### ISSUE THREAD

**Issue by xia-deng** [codedx/codepulse#22]
Upload jar file failed, just showed: Error: <html><head><title>Error</title></head><body> <h2>ERROR: </h2> <br> </body></html>

I am running this in docker container, and using the port 80.

I cannot see some more detail error message, so I am unable to find the reason.

**Comment by KenProle** [comment]
Code Pulse was designed to be run interactively on the host machine since it has many UI elements to it. We have not tested this for use in a headless container. Are you able to run this directly on the host instead?
