### ISSUE TITLE
Agent 2.6.2 Version throws Java Run Time SIGSEGV which causes JVM to exit

### ISSUE THREAD

**Issue by peddadap** [codedx/codepulse#23]
_We are trying to run code pulse on Enterprise Red Hat Linux 7.2  and on Spring Boot 2.x  on Java 8

After initially connecting to the Server the Agent causes JVM to crash
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=57980, tid=47654314198784
#
# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000_

**Comment by stevesalas** [comment]
Thank you for reporting this information. 

We have not previously tested tracing Spring Boot 2.x applications with Code Pulse running on Red Hat Enterprise Linux. To start troubleshooting this issue, we set up a Red Hat Enterprise Linux Server (see os-release contents below), installed Code Pulse, and successfully traced a Spring Boot 2.3 sample application created by following the Quickstart at https://spring.io/quickstart. Our server had OpenJDK 1.8.0_252 installed (see java version info below).

Is Code Pulse failing to run with every application you try? The issue you're experiencing may be specific to the application you're trying to trace. It would be helpful if we can first confirm that Code Pulse is working correctly in your environment by trying to trace the "Hello World!" sample application described at https://spring.io/quickstart.

---
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
