### ISSUE TITLE
Project upload limitation 500mb

### ISSUE THREAD

**Issue by shizzgar** [codedx/codepulse#24]
Hi, @KenProle! 

I'm working on developing java project, and it's more over 500mb
How can i enlarge this limatation? 
Is there maybe some lines of code in your project, that i can change 
And build it by my own? 
Maybe this one?

https://github.com/codedx/codepulse/blob/c6edc283a72877a3cb93865b397deea07adf3ad0/codepulse/src/main/scala/bootstrap/liftweb/FileUploadSetup.scala#L43

Additionaly, i need information, 
How can i build CodePulse on linux environment.

Also, i want to say, that your work is just awesome!
Tool looks preaty good, i can't wait to test my project with it!

**Comment by stevesalas** [comment]
Hello shizzgar,

Code Pulse version 2.7.0 was just released with support for raising the file upload limit. You can use the new `maxFileUploadSizeMebibytes` parameter in the `codepulseSettings.conf` file to specify the maximum file upload size. You can find that file in your `$HOME/.codepulse` directory. Code Pulse will create that file if it doesn't exist, and the new default version looks like this:

    cp {
        userSettings {
            #  Logging Level: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
            #  When not set, default logging level applies (logback.xml)
            logging {
                rootLoggingLevel=ERROR
                liftwebLoggingLevel=WARN
                codedxLoggingLevel=INFO
                bootstrapLoggingLevel=INFO
                secdecLoggingLevel=INFO
            }
            symbolService {
                port="49582"
                port=${?SYMBOL_SERVICE_PORT}
            }
            #  Determines whether Code Pulse can skip user acknowledgment of a trace that specifies a project ID
            skipUserAcknowledgment=false
            skipUserAcknowledgment=${?CODE_PULSE_TRACE_SKIP_ACK}
            maxFileUploadSizeMebibytes=500
            #  The port used to listen for agent connections
            tracePort=8765
            tracePort=${?CODE_PULSE_TRACE_PORT}
        }
    }

You'll need to restart Code Pulse after changing the value of `maxFileUploadSizeMebibytes`.

The development environment setup instructions have been updated for this release. If you'd like to compile and run Code Pulse on Linux, follow the [setup instructions](https://github.com/codedx/codepulse/blob/master/readme.md) and skip any steps that are Windows-specific.

Thanks for the kind words and let us know if you have any difficulty using the new version.
